### ISSUE TITLE
Please add license information

### ISSUE THREAD

**Issue by Ploy-XIV** [sinofool/build-openssl-ios#3]
Could you please add a license to your project?

I'd like to use it for an iOS app that will be distributed by the App Store, and I need to be sure I can use your script under a license compatible to the App Store Terms for developers.

Github has some documentation on how to best add a license to a project here: [https://help.github.com/articles/licensing-a-repository/](https://help.github.com/articles/licensing-a-repository/).

Thank you for your consideration, and the effort you have already put into this!

**Comment by sinofool** [comment]
Thanks for your advice. It will be MIT License for this project. I will add
the license file when I back to work next week.

**Comment by sinofool** [comment]
Added
